language: ruby
cache: bundler
sudo: false
rvm:
  - 2.1.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
    - ubuntu-12.04-LTS
    - ubuntu-14.04-LTS    
script:
  - bundle exec rake default
